/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.portafolio.vista;

import cl.duoc.portafolio.controller.TipoUsuarioController;
import cl.duoc.portafolio.entities.TipoUsuario;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author lun4t1k0
 */
public class DlgCrearTipoUsuario extends javax.swing.JDialog {

    private final static Logger logger = Logger.getLogger(DlgCrearTipoUsuario.class);
    private static TipoUsuarioView tipoUsuarioView = null;
    private static TipoUsuario tius = null;

    /**
     * Creates new form DlgCrearTipoUsuario
     */
    public DlgCrearTipoUsuario(TipoUsuarioView uipoUsuarioViewP, boolean modal, TipoUsuario tipoUsu) {
        tipoUsuarioView = uipoUsuarioViewP;
        tius = tipoUsu;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
        if (tius != null) {
            this.cargarDatos(tipoUsu);
        }
    }

    private void cargarDatos(TipoUsuario tipoUsu) {
        this.txtTipoNombreUsuario.setText(tipoUsu.getglosa_tipo_usuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreTipoUsuario = new javax.swing.JLabel();
        txtTipoNombreUsuario = new javax.swing.JTextField();
        btnCrearTipoUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblTitulo.setText("Crear Usuario");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel4.setText("Ingrese el nombre del nuevo tipo de usuario");

        lblNombreTipoUsuario.setText("Nombre Tipo Usuario :");

        btnCrearTipoUsuario.setText("Crear");
        btnCrearTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoUsuarioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreTipoUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(txtTipoNombreUsuario))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearTipoUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTipoUsuario)
                    .addComponent(txtTipoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearTipoUsuario)
                    .addComponent(btnCancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoUsuarioActionPerformed
        // TODO add your handling code here:
        TipoUsuarioController tipoUsuCont = new TipoUsuarioController();
        try {
            //Acción actualizar o crear
            if (tius != null) {
                //Actualizar
                tius.setglosa_tipo_usuario(this.txtTipoNombreUsuario.getText().trim());
                
                //incorporar rut de navegación
                //uni.setRut_actualizacion("");

                boolean resultado = tipoUsuCont.actualizarTipoUsuario(tius);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error actualizando Tipo de Usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.dispose();
                }
            } else {
                //Crear
                tius.setglosa_tipo_usuario(this.txtTipoNombreUsuario.getText().trim());
                
                //incorporar rut de navegación
                //uni.setRut_creacion("");

                boolean resultado = tipoUsuCont.crearTipoUsuario(tius);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error creando Tipo de Usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.dispose();
                }
            }
        } catch (Exception e) {
            logger.error("Error grave en el mantenedor de Tipo de Usuario.", e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            tipoUsuCont = null;
            tius = null;
        }
    }//GEN-LAST:event_btnCrearTipoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCrearTipoUsuario dialog = new DlgCrearTipoUsuario(tipoUsuarioView, true, tius);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearTipoUsuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNombreTipoUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtTipoNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
