/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.portafolio.vista;

import cl.duoc.portafolio.controller.TipoUsuarioController;
import cl.duoc.portafolio.controller.UnidadInternaController;
import cl.duoc.portafolio.entities.Usuario;
import cl.duoc.portafolio.controller.UsuarioController;
import cl.duoc.portafolio.controller.ValidacionesController;
import cl.duoc.portafolio.entities.TipoUsuario;
import cl.duoc.portafolio.entities.UnidadInterna;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Esteban Perez
 */
public class DlgCrearUsuario extends javax.swing.JDialog {

    private final static Logger logger = Logger.getLogger(DlgCrearUsuario.class);
    private static UsuarioView usuarioView = null;
    private static Usuario usu = null;

    /**
     * Creates new form DirtyDialog
     */
    public DlgCrearUsuario(UsuarioView usuarioViewP, boolean modal, Usuario usuario) {
        //super(parent, modal);
        usuarioView = usuarioViewP;
        usu = usuario;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
        if (usu != null) {
            this.cargarDatosUsuario(usuario);
        }
        this.cargaListaTipoUsuario(usuario);
    }

    private void cargarDatosUsuario(Usuario usu) {
        this.txtRut.setText(usu.getRut());
        this.txtNombre.setText(usu.getNombre());
        this.txtApellidoP.setText(usu.getApellidop());
        this.txtApellidoM.setText(usu.getApellidom());
        this.ftfFechaIngreso.setText(usu.getFecha_ingreso());
        this.ftfFechaContrato.setText(usu.getFecha_contrato());
    }
    
    private void cargaListaUnidadInterna(Usuario usu){
        UnidadInternaController unidadInternaController = null;
        try {
            List<UnidadInterna> listaUnidadInternas = unidadInternaController.getUnidadInternas();
            //carga datos a la tabla, fila por fila
            for (UnidadInterna ui : listaUnidadInternas) {
                //jcbUnidadInterna.addItem(ui);
                //jcbUnidadInterna.addItem(ui.getId_unidad_interna(),ui.getGlosa_unidad_interna());
                //jcbUnidadInterna.addItem(new Item(ui.getId_unidad_interna(),ui.getGlosa_unidad_interna()));
            }
            if (usu != null) {
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            unidadInternaController = null;
        }
    }
    
    private void cargaListaTipoUsuario(Usuario usu){
        TipoUsuarioController tipoUsuarioController = null;
        //RelUsuarioTipoUsuController relUsuarioTipoUsuController = null;

        
        try {
            tipoUsuarioController = new TipoUsuarioController();
            //lista de tipos de usuario
            List<TipoUsuario> listaTipoUsuarios = tipoUsuarioController.getTipoUsuarios();
            //pasar la lista al jList que desplagará los datos
            //this.jlTipoUsuario.setModel(listaTipoUsuarios);
            //this.jlTipoUsuario.setModel((AbstractListModel<String>)listaTipoUsuarios);
            
            //si la ventana edita, precargar las selecciones 
            if (usu != null) {
                //buscar tipos de usuario del usuario
                //seleccionar tipos de usuario, en base a la lista anterior
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            tipoUsuarioController = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        psfClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        ftfFechaIngreso = new javax.swing.JFormattedTextField();
        lblFechaContrato = new javax.swing.JLabel();
        ftfFechaContrato = new javax.swing.JFormattedTextField();
        lblClaveRepite = new javax.swing.JLabel();
        psfClaveRepite = new javax.swing.JPasswordField();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlTipoUsuario = new javax.swing.JList<>();
        lblUnidadInterna = new javax.swing.JLabel();
        jcbUnidadInterna = new javax.swing.JComboBox<>();
        lblEsJefeUnidad = new javax.swing.JLabel();
        chbEsJefeUnidad = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Aceptar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        lblApellidoP.setText("Apellido Paterno");

        lblApellidoM.setText("Apellido Materno");

        lblClave.setText("Clave");

        jLabel1.setText("Fecha Ingreso");

        ftfFechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        lblFechaContrato.setText("Fecha Contrato");

        ftfFechaContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftfFechaContrato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfFechaContratoFocusLost(evt);
            }
        });

        lblClaveRepite.setText("Reingrese Clave");

        lblRut.setText("Rut");

        txtRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRutFocusLost(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblTitulo.setText("Crear Usuario");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel4.setText("Ingrese los campos solicitados");

        lblTipoUsuario.setText("Tipo de Usuario");

        jScrollPane1.setViewportView(jlTipoUsuario);

        lblUnidadInterna.setText("Unidad Interna");

        lblEsJefeUnidad.setText("Jefe de Unidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClaveRepite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipoUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ftfFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ftfFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(psfClaveRepite, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(psfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1))))))
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(312, 312, 312))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(615, 615, 615))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEsJefeUnidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(207, 207, 207)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbUnidadInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chbEsJefeUnidad)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblUnidadInterna)
                                    .addGap(323, 323, 323))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psfClaveRepite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClaveRepite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaContrato)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(282, 282, 282)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadInterna)
                    .addComponent(jcbUnidadInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEsJefeUnidad)
                    .addComponent(chbEsJefeUnidad))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        UsuarioController usrCont = new UsuarioController();
        try {
            //Acción actualizar o crear
            if (usu != null) {
                //Actualizar
                usu.setRut(this.txtRut.getText().trim());
                usu.setNombre(this.txtNombre.getText().trim());
                usu.setFecha_ingreso(this.ftfFechaIngreso.getText().trim());
                usu.setFecha_contrato(this.ftfFechaContrato.getText().trim());
                usu.setApellidop(this.txtApellidoP.getText().trim());
                usu.setApellidom(this.txtApellidoM.getText().trim());

                //validación clave
                if (!new String(this.psfClave.getPassword()).trim().isEmpty()) {
                    if (new String(this.psfClaveRepite.getPassword()).trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Debe ingresar la confirmación de la clave.", "Error", JOptionPane.ERROR_MESSAGE);
                        this.psfClaveRepite.requestFocus();
                        return;
                    } else if (!new String(this.psfClaveRepite.getPassword()).trim().equals(new String(this.psfClave.getPassword()).trim())) {
                        JOptionPane.showMessageDialog(this, "Las claves ingresadas no son identicas.", "Error", JOptionPane.ERROR_MESSAGE);
                        this.psfClave.requestFocus();
                        this.psfClaveRepite.setText("");
                        return;
                    } else {
                        usu.setPassword(new String(this.psfClave.getPassword()).trim());
                    }
                }

                //incorporar rut de navegación
                //usu.setRut_actualizacion("");
                
                boolean resultado = usrCont.actualizarUsuario(usu);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error actualizando Usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    //AGREGAR RELACION USURIO-TIPOS DE USUARIO
                    //AGREGAR RELACION USUARIO-UNIDAD INTERNA (INCLUYE JEFE)
                    this.dispose();
                }
            } else {
                //valido que la clave no venga vacía
                if (new String(this.psfClave.getPassword()).trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar una clave.", "Error", JOptionPane.ERROR_MESSAGE);
                    this.psfClave.requestFocus();
                    this.psfClaveRepite.setText("");
                    return;
                }

                //Crear
                usu = new Usuario();
                usu.setRut(this.txtRut.getText().trim());
                usu.setNombre(this.txtNombre.getText().trim());
                usu.setFecha_ingreso(this.ftfFechaIngreso.getText().trim());
                usu.setFecha_contrato(this.ftfFechaContrato.getText().trim());
                usu.setApellidop(this.txtApellidoP.getText().trim());
                usu.setApellidom(this.txtApellidoM.getText().trim());

                //validación clave
                if (!new String(this.psfClave.getPassword()).trim().isEmpty()) {
                    if (new String(this.psfClaveRepite.getPassword()).trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Debe ingresar la confirmación de la clave.", "Error", JOptionPane.ERROR_MESSAGE);
                        this.psfClaveRepite.requestFocus();
                        return;
                    } else if (!new String(this.psfClaveRepite.getPassword()).trim().equals(new String(this.psfClave.getPassword()).trim())) {
                        JOptionPane.showMessageDialog(this, "Las claves ingresadas no son identicas.", "Error", JOptionPane.ERROR_MESSAGE);
                        this.psfClave.requestFocus();
                        this.psfClaveRepite.setText("");
                        return;
                    } else {
                        usu.setPassword(new String(this.psfClave.getPassword()).trim());
                    }
                }
                
                //incorporar rut de navegación
                //usu.setRut_creacion("");

                boolean resultado = usrCont.crearUsuario(usu);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error creando Usuario.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.dispose();
                }
            }
        } catch (Exception e) {
            logger.error("Error grave en el mantenedor de usuario.", e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            usrCont = null;
            usu = null;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutFocusLost
        // TODO add your handling code here:
        ValidacionesController valid = new ValidacionesController();
        try {
            boolean valido = valid.validarRut(txtRut.getText().trim());
            
       
        if (!valido) {
            JOptionPane.showMessageDialog(this, "El Rut no es valido", "Error",JOptionPane.ERROR_MESSAGE);
        } else {
            String formato = valid.FormatearRUT(txtRut.getText());
            txtRut.setText(formato);
        }
        } catch (Exception e) {
        }
        finally{
            valid = null;
        }
       
    }//GEN-LAST:event_txtRutFocusLost

    private void ftfFechaContratoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfFechaContratoFocusLost
        // TODO add your handling code here:
         ValidacionesController valid = new ValidacionesController();
         try {
             String resultado = valid.ValidarFecha(ftfFechaIngreso.getText().trim(), ftfFechaContrato.getText().trim());
             if (!resultado.isEmpty()) {
               JOptionPane.showMessageDialog(this, resultado, "Error",JOptionPane.ERROR_MESSAGE);
             } 
        } catch (Exception e) {
        }finally{
             valid = null;
         }
 
        
    }//GEN-LAST:event_ftfFechaContratoFocusLost

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
         ValidacionesController valid = new ValidacionesController();
        try {
            String resultado = null;
            resultado = valid.ValidarLargoCampo(50, txtNombre.getText().length());
            if (!resultado.isEmpty()) {
                JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE );
                
            } else {
            }
        } catch (Exception e) {
        }finally{
           valid = null;
       }
    }//GEN-LAST:event_txtNombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCrearUsuario dialog = new DlgCrearUsuario(usuarioView, true, usu);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chbEsJefeUnidad;
    private javax.swing.JFormattedTextField ftfFechaContrato;
    private javax.swing.JFormattedTextField ftfFechaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbUnidadInterna;
    private javax.swing.JList<String> jlTipoUsuario;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblClaveRepite;
    private javax.swing.JLabel lblEsJefeUnidad;
    private javax.swing.JLabel lblFechaContrato;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidadInterna;
    private javax.swing.JPasswordField psfClave;
    private javax.swing.JPasswordField psfClaveRepite;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
