/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.portafolio.vista;
import cl.duoc.portafolio.controller.TipoAprobacionController;
import cl.duoc.portafolio.entities.TipoAprobacion;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
/**
 *
 * @author lun4t1k0
 */
public class DlgCrearTipoAprobacion extends javax.swing.JDialog {
    
    private final static Logger logger = Logger.getLogger(DlgCrearTipoAprobacion.class);
    private static TipoAprobacionView tipoAprobacionView = null;
    private static TipoAprobacion tipAprobacion = null;
    /**
     * Creates new form DlgCrearTipoAprobacion
     */
    public DlgCrearTipoAprobacion(TipoAprobacionView tipoAprobacionViewP, boolean modal, TipoAprobacion tipoAprobacion) {
        tipoAprobacionView = tipoAprobacionViewP;
        tipAprobacion = tipoAprobacion;
        this.setModal(modal);
        initComponents();
        setLocationRelativeTo(this);
        if (tipAprobacion != null) {
            this.cargarDatos(tipAprobacion);
        }
    }

    private void cargarDatos(TipoAprobacion tipoAprobacion) {
        this.txtTipoNombreAprobacion.setText(tipoAprobacion.getGlosa_tipo_aprobacion());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreTipoAprobacion = new javax.swing.JLabel();
        txtTipoNombreAprobacion = new javax.swing.JTextField();
        btnCrearTipoAprobacion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblTitulo.setText("Crear tipo Aprobacion ");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel4.setText("Ingrese el nombre del nuevo tipo de aprobacion");

        lblNombreTipoAprobacion.setText("Nombre Tipo Aprobacion:");

        btnCrearTipoAprobacion.setText("Aceptar");
        btnCrearTipoAprobacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoAprobacionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombreTipoAprobacion)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoNombreAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearTipoAprobacion)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTipoAprobacion)
                    .addComponent(txtTipoNombreAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearTipoAprobacion)
                    .addComponent(btnCancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearTipoAprobacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoAprobacionActionPerformed
        // TODO add your handling code here:
        TipoAprobacionController tipoAprobacionCont = new TipoAprobacionController();
        try {
            //Acción actualizar o crear
            if (tipAprobacion != null) {
                //Actualizar
                tipAprobacion.setGlosa_tipo_aprobacion(this.txtTipoNombreAprobacion.getText().trim());
                
                //incorporar rut de navegación
                //uni.setRut_actualizacion("");

                boolean resultado = tipoAprobacionCont.actualizarTipoAprobacion(tipAprobacion);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error actualizando Tipo de Aprobación.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.dispose();
                }
            } else {
                //Crear
                tipAprobacion = new TipoAprobacion();
                tipAprobacion.setGlosa_tipo_aprobacion(this.txtTipoNombreAprobacion.getText().trim());
                
                //incorporar rut de navegación
                //uni.setRut_creacion("");

                boolean resultado = tipoAprobacionCont.crearTipoAprobacion(tipAprobacion);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error creando Tipo de Aprobación.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.dispose();
                }
            }
        } catch (Exception e) {
            logger.error("Error grave en el mantenedor de Tipo de Aprobación", e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            tipoAprobacionCont = null;
            tipAprobacion = null;
        }
    }//GEN-LAST:event_btnCrearTipoAprobacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoAprobacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoAprobacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoAprobacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCrearTipoAprobacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCrearTipoAprobacion dialog = new DlgCrearTipoAprobacion(tipoAprobacionView, true, tipAprobacion);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearTipoAprobacion;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNombreTipoAprobacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtTipoNombreAprobacion;
    // End of variables declaration//GEN-END:variables
}
