/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.portafolio.vista;

import javax.swing.JFrame;

/**
 *
 * @author Edo
 */
public class Principal extends javax.swing.JFrame {

    private UsuarioView usuarioView = null;
    private UnidadInternaView unidadInternaView = null;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnUsuario = new javax.swing.JMenu();
        imnUsuario = new javax.swing.JMenuItem();
        mnUnidadInterna = new javax.swing.JMenu();
        imnUnidadInterna = new javax.swing.JMenuItem();
        mnCalendarioHabil = new javax.swing.JMenu();
        imnCalendarioHabil = new javax.swing.JMenuItem();
        mnFeriadoManual = new javax.swing.JMenu();
        imnFeriadoManual = new javax.swing.JMenuItem();
        mnMenu = new javax.swing.JMenu();
        imnMenu = new javax.swing.JMenuItem();
        mnTipoUso = new javax.swing.JMenu();
        imnTipoUso = new javax.swing.JMenuItem();
        mnTipoAprobacion = new javax.swing.JMenu();
        imnTipoAprobacion = new javax.swing.JMenuItem();
        mnTipoDiaLibre = new javax.swing.JMenu();
        imnTipoDiaLibre = new javax.swing.JMenuItem();
        mnTipoUsuario = new javax.swing.JMenu();
        imnTipoUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1296, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        mnUsuario.setText("Usuario");

        imnUsuario.setText("Administrar");
        imnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnUsuarioActionPerformed(evt);
            }
        });
        mnUsuario.add(imnUsuario);

        jMenuBar1.add(mnUsuario);

        mnUnidadInterna.setText("Unidad Interna");

        imnUnidadInterna.setText("Administrar");
        imnUnidadInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnUnidadInternaActionPerformed(evt);
            }
        });
        mnUnidadInterna.add(imnUnidadInterna);

        jMenuBar1.add(mnUnidadInterna);

        mnCalendarioHabil.setText("Calendario");

        imnCalendarioHabil.setText("Administrar");
        imnCalendarioHabil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnCalendarioHabilActionPerformed(evt);
            }
        });
        mnCalendarioHabil.add(imnCalendarioHabil);

        jMenuBar1.add(mnCalendarioHabil);

        mnFeriadoManual.setText("Feriado");

        imnFeriadoManual.setText("Administrar");
        imnFeriadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnFeriadoManualActionPerformed(evt);
            }
        });
        mnFeriadoManual.add(imnFeriadoManual);

        jMenuBar1.add(mnFeriadoManual);

        mnMenu.setText("Menú");

        imnMenu.setText("Administrar");
        imnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnMenuActionPerformed(evt);
            }
        });
        mnMenu.add(imnMenu);

        jMenuBar1.add(mnMenu);

        mnTipoUso.setText("Tipo de Uso");

        imnTipoUso.setText("Administrar");
        imnTipoUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnTipoUsoActionPerformed(evt);
            }
        });
        mnTipoUso.add(imnTipoUso);

        jMenuBar1.add(mnTipoUso);

        mnTipoAprobacion.setText("Tipo Aprobación");

        imnTipoAprobacion.setText("Administrar");
        imnTipoAprobacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnTipoAprobacionActionPerformed(evt);
            }
        });
        mnTipoAprobacion.add(imnTipoAprobacion);

        jMenuBar1.add(mnTipoAprobacion);

        mnTipoDiaLibre.setText("Tipo Día Libre");

        imnTipoDiaLibre.setText("Administrar");
        imnTipoDiaLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnTipoDiaLibreActionPerformed(evt);
            }
        });
        mnTipoDiaLibre.add(imnTipoDiaLibre);

        jMenuBar1.add(mnTipoDiaLibre);

        mnTipoUsuario.setText("Tipo Usuario");

        imnTipoUsuario.setText("Administrar");
        imnTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnTipoUsuarioActionPerformed(evt);
            }
        });
        mnTipoUsuario.add(imnTipoUsuario);

        jMenuBar1.add(mnTipoUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnUsuarioActionPerformed
        // TODO add your handling code here:
        if (this.getUsuarioView() == null) {
            UsuarioView esrv = new UsuarioView();
            this.setUsuarioView(esrv);
            this.pnlPrincipal.add(this.getUsuarioView());
            this.getUsuarioView().show();
        } else {
            if (this.getUsuarioView().isVisible() == false) {
                UsuarioView esrv = new UsuarioView();
                this.setUsuarioView(esrv);
                this.pnlPrincipal.add(this.getUsuarioView());
                this.getUsuarioView().show();
            }
        }
    }//GEN-LAST:event_imnUsuarioActionPerformed

    private void imnUnidadInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnUnidadInternaActionPerformed
        // TODO add your handling code here:
        if (this.getUnidadInternaView() == null) {
            UnidadInternaView esrv = new UnidadInternaView();
            this.setUnidadInternaView(esrv);
            this.pnlPrincipal.add(this.getUnidadInternaView());
            this.getUnidadInternaView().show();
        } else {
            if (this.getUnidadInternaView().isVisible() == false) {
                UnidadInternaView esrv = new UnidadInternaView();
                this.setUnidadInternaView(esrv);
                this.pnlPrincipal.add(this.getUnidadInternaView());
                this.getUnidadInternaView().show();
            }
        }
    }//GEN-LAST:event_imnUnidadInternaActionPerformed

    private void imnCalendarioHabilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnCalendarioHabilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnCalendarioHabilActionPerformed

    private void imnFeriadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnFeriadoManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnFeriadoManualActionPerformed

    private void imnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnMenuActionPerformed

    private void imnTipoUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnTipoUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnTipoUsoActionPerformed

    private void imnTipoAprobacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnTipoAprobacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnTipoAprobacionActionPerformed

    private void imnTipoDiaLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnTipoDiaLibreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnTipoDiaLibreActionPerformed

    private void imnTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imnTipoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public UsuarioView getUsuarioView() {
        return usuarioView;
    }

    public void setUsuarioView(UsuarioView usuarioView) {
        this.usuarioView = usuarioView;
    }

    public UnidadInternaView getUnidadInternaView() {
        return unidadInternaView;
    }

    public void setUnidadInternaView(UnidadInternaView unidadInternaView) {
        this.unidadInternaView = unidadInternaView;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imnCalendarioHabil;
    private javax.swing.JMenuItem imnFeriadoManual;
    private javax.swing.JMenuItem imnMenu;
    private javax.swing.JMenuItem imnTipoAprobacion;
    private javax.swing.JMenuItem imnTipoDiaLibre;
    private javax.swing.JMenuItem imnTipoUso;
    private javax.swing.JMenuItem imnTipoUsuario;
    private javax.swing.JMenuItem imnUnidadInterna;
    private javax.swing.JMenuItem imnUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnCalendarioHabil;
    private javax.swing.JMenu mnFeriadoManual;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenu mnTipoAprobacion;
    private javax.swing.JMenu mnTipoDiaLibre;
    private javax.swing.JMenu mnTipoUso;
    private javax.swing.JMenu mnTipoUsuario;
    private javax.swing.JMenu mnUnidadInterna;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JDesktopPane pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
