/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.portafolio.vista;

import cl.duoc.portafolio.controller.UsuarioController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import cl.duoc.portafolio.entities.Usuario;
import java.awt.Dialog;
import java.awt.Frame;

/**
 *
 * @author Edo
 */
public class UsuarioView extends javax.swing.JInternalFrame {

    private final static Logger logger = Logger.getLogger(Index.class);

    /**
     * Creates new form Usuario
     */
    public UsuarioView() {
        initComponents();
        cargaTabla();
    }

    /**
     * método para refrescar la tabla
     */
    private void cargaTabla() {
        UsuarioController usuCont = null;
        try {
            usuCont = new UsuarioController();
            String inactivos = chbInactivos.isSelected() ? "-1" : "1";
            List<cl.duoc.portafolio.entities.Usuario> listaUsuarios = usuCont.getUsuarios(inactivos);
            String col[] = {"Rut", "Nombre", "Apellido P", "Apellido M", "Clave", "Fecha Contrato", "Fecha Ingreso", "Activo"};

            DefaultTableModel tableModel = (DefaultTableModel) this.tblUsuarios.getModel();
            tableModel.setRowCount(0);//al setear en cero, elimina de verdad todas las filas del objeto JTable (sean o no las que vienen por defecto)
            tableModel.setColumnIdentifiers(col);

            for (cl.duoc.portafolio.entities.Usuario usu : listaUsuarios) {
                Object[] row = new Object[]{usu.getRut(), usu.getNombre(), usu.getApellidop(), usu.getApellidom(), usu.getPassword(), usu.getFecha_contrato(), usu.getFecha_ingreso(), usu.getFlag_activo() == 1 ? "Si" : "No"};
                tableModel.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            usuCont = null;
        }
    }

    /**
     * método para encontrar el index, usando el nombre de la columna
     */
    private int getIndexColumnByName(javax.swing.JTable tabla, String nombre) {
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            if (tabla.getColumnName(i).equals(nombre)) {
                return i;
            }
        }
        return -1;
    }

    /**
     * método que limpia los elementos de edición (textbox y otros)
     */
    private void limpiaCampos() {
//        this.txtRut.setText(null);
//        this.txtNombre.setText(null);
//        this.pswPassword.setText(null);
//        this.ftfFechaIngreso.setText(null);
//        this.ftfFechaContrato.setText(null);
//        this.txtApellidoP.setText(null);
//        this.txtApellidoM.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarUsuarios = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        chbInactivos = new javax.swing.JCheckBox();
        btnActivar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Mantenedor de usuario");
        setPreferredSize(new java.awt.Dimension(1240, 768));

        btnListarUsuarios.setText("Actualizar");
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        tblUsuarios.setAutoCreateRowSorter(true);
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tblUsuarios);

        chbInactivos.setText("Incluir inactivos");
        chbInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbInactivosActionPerformed(evt);
            }
        });

        btnActivar.setText("Activar / Desactivar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbInactivos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbInactivos)
                        .addComponent(btnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
//        UsuarioController usuCont = null;
//        try{
//            usuCont = new UsuarioController();
//            Usuario usu = new Usuario();
//            usu.setRut(this.txtRut.getText().trim());
//            usu.setNombre(this.txtNombre.getText().trim());
//            usu.setPassword(new String(this.pswPassword.getPassword()));
//            usu.setFecha_ingreso(this.ftfFechaIngreso.getText());
//            usu.setFecha_contrato(this.ftfFechaContrato.getText());
//            usu.setApellidop(this.txtApellidoP.getText());
//            usu.setApellidom(this.txtApellidoM.getText());
//            boolean resultado = usuCont.crearUsuario(usu);
//            
//            if(!resultado){
//                JOptionPane.showMessageDialog(this, "Error grave creando Usuario.", "Error", JOptionPane.ERROR_MESSAGE);
//            }else{
//                this.limpiaCampos();
//                this.cargaTabla();
//                JOptionPane.showMessageDialog(this, "Usuario creado correctamente.");
//            }
//        }catch(Exception e){
//            logger.error("Error grave creando usuario.", e);
//            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }finally{
//            usuCont = null;
//        }

        try {
            DlgCrearUsuario dlg = new DlgCrearUsuario(this, true, null);
            dlg.setTitle("Agregar Usuario");
            //this.add(dlg);
            dlg.setVisible(true);
        } catch (Exception e) {
            logger.error("Error grave creando usuario.", e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        // TODO add your handling code here:
        UsuarioController usuarioCont = null;
        try {
            usuarioCont = new UsuarioController();
            if (this.tblUsuarios.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Error: Debe seleccionar un usuario para Actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String rut = String.valueOf(this.tblUsuarios.getValueAt(this.tblUsuarios.getSelectedRow(), 0)).trim();
                Usuario usu = usuarioCont.obtenerUsuario(rut);
                DlgCrearUsuario dlg = new DlgCrearUsuario(this, true, usu);
                dlg.setTitle("Modificar Usuario");
                dlg.setVisible(true);
            }
        } catch (Exception e) {
            logger.error("Error grave actualizando usuario.", e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            usuarioCont = null;
        }
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        UsuarioController usuCont = null;
        try {
            usuCont = new UsuarioController();
            if (this.tblUsuarios.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Error: Debe seleccionar un usuario para Activar / Desactivar.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String rut = String.valueOf(this.tblUsuarios.getValueAt(this.tblUsuarios.getSelectedRow(), 0)).trim();
                //busco valor de "activo"
                //int activo = String.valueOf(this.tblUsuarios.getValueAt(this.tblUsuarios.getSelectedRow(), getIndexColumnByName(this.tblUsuarios, "Activo"))).trim().toLowerCase() == "si" ? 1 : 0;

                //busco valor de "activo", pero INVERTIDO, porque lo que quiere el usuario en esta acción, es setear lo opuesto al estado actual
                int activo = String.valueOf(this.tblUsuarios.getValueAt(this.tblUsuarios.getSelectedRow(), getIndexColumnByName(this.tblUsuarios, "Activo"))).trim().toLowerCase() == "si" ? 0 : 1;

                boolean resultado = usuCont.activarUsuario(rut, activo);
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "Error no controlado ", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.limpiaCampos();
                    this.cargaTabla();
                    if (activo == 0) {
                        JOptionPane.showMessageDialog(this, "Usuario desactivado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Usuario activado correctamente.");
                    }
                }
            }
        } catch (Exception e) {
            logger.error("Error grave creando usuario.", e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            usuCont = null;
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void chbInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbInactivosActionPerformed
        // TODO add your handling code here:
        this.cargaTabla();
    }//GEN-LAST:event_chbInactivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JCheckBox chbInactivos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
